id: IBA79675F
legacy_id: P000495
ocr_import_info:
  bdrc_scan_id: W4CZ65553
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T13:37:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:55:32.737446+00:00'
last_modified: 2022-09-04 04:55:38.481033
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ65553
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ65553
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་ཐོར་བུ། བློ་བཟང་འོད་ཟེར།
  author: རྗེ་བཙུན་བློ་བཟང་འོད་ཟེར།
statistics:
  ocr_word_mean_confidence_index: 0.6907754881863063
  ocr_word_median_confidence_index: 0.7599999904632568
quality: null
bases:
  I4CZ65583:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ65583
      total_pages: 124
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ65583.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6907754881863063
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
