id: IBA79675F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:38:00+00:00'
last_modified: '2022-06-16T04:11:54.199979+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ65553
  title: གསུང་ཐོར་བུ། བློ་བཟང་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8A7B:
      image_group_id: I4CZ65583
      title: Volume 1 of gsung thor bu/ blo bzang 'od zer/
      total_pages: 124
      order: 1
      base_file: 8A7B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
